core/urls.py

from django.urls import path
from .import views


app_name = 'core'


urlpatterns = [
    path('staff_operations_dashboard/', views.staff_operations_dashboard, name='staff_operations_dashboard'),
    path('home/', views.home, name='home'),
    path('', views.dashboard, name='dashboard'),
    path('core_dashboard/', views.core_dashboard, name='core_dashboard'),
    path('only_core_dashboard/', views.only_core_dashboard, name='only_core_dashboard'),
    path('view_employee/', views.view_employee, name='view_employee'),
    path('employee_list/', views.employee_list, name='employee_list'),
   
    path('manage_department/', views.manage_department, name='manage_department'),  
    path('manage_location/', views.manage_location, name='manage_location'),

    path('create_positionn/', views.manage_position, name='create_position'),    
    path('update_positionn/<int:id>/', views.manage_position, name='update_position'),    
    path('delete_position/<int:id>/', views.delete_position, name='delete_position'),  
    path('position_details/<int:id>/', views.position_details, name='position_details'),  

    path('create_job_requirement/', views.manage_job_requirement, name='create_job_requirement'),    
    path('update_job_requirement/<int:id>/', views.manage_job_requirement, name='update_job_requirement'),    
    path('delete_job_requirement/<int:id>/', views.delete_job_requirement, name='delete_job_requirement'),  

    path('create_job_description/', views.manage_job_description, name='create_job_description'),    
    path('update_job_description/<int:id>/', views.manage_job_description, name='update_job_description'),    
    path('delete_job_description/<int:id>/', views.delete_job_descriptiont, name='delete_job_description'),  

    path('create_company/', views.create_company, name='create_company'),
    path('update_company/<int:id>/', views.create_company, name='update_company'),
    path('delete_company/<int:id>/', views.delete_company,  name='delete_company'),    
    
    path('manage_employee/', views.manage_employee, name='manage_employee'),
    path('update_employee/<int:id>/', views.manage_employee, name='update_employee'),
    path('delete_employee/<int:id>/', views.delete_employee,  name='delete_employee'),    

    path('manage_doctor/', views.manage_doctor, name='manage_doctor'),
    path('update_doctor/<int:id>/', views.manage_doctor, name='update_doctor'),
    path('delete_doctor/<int:id>/', views.delete_doctor,  name='delete_doctor'),   

    path('manage_nurse/', views.manage_nurse, name='manage_nurse'),
    path('update_nurse/<int:id>/', views.manage_nurse, name='update_nurse'),
    path('delete_nurse/<int:id>/', views.delete_nurse,  name='delete_nurse'),   
            
    path('add_notice/', views.add_notice, name='add_notice'), 
    path('view_notices/', views.view_notices, name='view_notices'),  
    path('all_qc/', views.all_qc, name='all_qc'),
        
    path('create_salary/', views.create_salary, name='create_salary'),
    path('download_salary/', views.download_salary, name='download_salary'),

    path('view_employee_changes/', views.view_employee_changes, name='view_employee_changes'),
    path('download_employee_changes/', views.download_employee_changes, name='download_employee_changes'),

    path('view_employee_changes_single/<int:employee_id>/', views.view_employee_changes_single, name='view_employee_changes_single'),
    
    path('preview_pay_slip/<int:employee_id>/', views.preview_pay_slip, name='preview_pay_slip'),
    path('generate_and_send_pay_slip/<int:employee_id>/', views.generate_and_send_pay_slip, name='generate_and_send_pay_slip'),
        
    path('preview_salary_certificate/<int:employee_id>/', views.preview_salary_certificate, name='preview_salary_certificate'),
    path('generate_and_send_salary_certificate/<int:employee_id>/', views.generate_and_send_salary_certificate, name='generate_and_send_salary_certificate'),
          
    path('preview_experience_certificate/<int:employee_id>/', views.preview_experience_certificate, name='preview_experience_certificate'),
    path('generate_and_send_experience_certificate/<int:employee_id>/', views.generate_and_send_experience_certificate, name='generate_and_send_experience_certificate'),
      
    path('create_company_policy/', views.manage_company_policy, name='create_company_policy'),
    path('update_company_policy/<int:id>/', views.manage_company_policy, name='update_company_policy'),
    path('delete_company_policy/<int:id>/', views.delete_company_policy, name='delete_company_policy'),   

    path('create_salary_structure/', views.manage_salary_structure, name='create_salary_structure'),
    path('update_salary_structure/<int:id>/', views.manage_salary_structure, name='update_salary_structure'),
    path('delete_salary_structure/<int:id>/', views.delete_salary_structure, name='delete_salary_structure'),   
    
    path('create_festival/', views.manage_festival, name='create_festival'),
    path('update_festival/<int:id>/', views.manage_festival, name='update_festival'),
    path('delete_festival/<int:id>/', views.delete_festival, name='delete_festival'),   

    path('create_performance_bonus/', views.manage_performance_bonus, name='create_performance_bonus'),
    path('update_performance_bonus/<int:id>/', views.manage_performance_bonus, name='update_performance_bonus'),
    path('delete_performance_bonus/<int:id>/', views.delete_performance_bonus, name='delete_performance_bonus'),   


]

leavemanagement/urls.py

from django.urls import path
from .import views


app_name = 'leavemanagement'


urlpatterns = [

    path('create_attendance_policy/', views.manage_attendance_policy, name='create_attendance_policy'),
    path('update_attendance_policy/<int:id>/', views.manage_attendance_policy, name='update_attendance_policy'),
    path('delete_attendance_policy/<int:id>/', views.delete_attendance_policye, name='delete_attendance_policy'), 
    
    path('view_attendance/', views.view_attendance, name='view_attendance'),
    path('attendance_input/', views.attendance_input, name='attendance_input'),
    path('update_attendance/<int:employee_id>/', views.update_attendance, name='update_attendance'), 
   
    path('create_leave_type/', views.manage_leave_type, name='create_leave_type'),
    path('update_leave_type/<int:id>/', views.manage_leave_type, name='update_leave_type'),
    path('delete_leave_type/<int:id>/', views.delete_leave_type, name='delete_leave_type'), 

    path('apply_leave/', views.apply_leave, name='apply_leave'),
    path('leave_history/', views.leave_history, name='leave_history'),
    path('pending_leave_list/', views.pending_leave_list, name='pending_leave_list'),
    path('approve_leave/<int:leave_id>/', views.approve_leave, name='approve_leave'),  
    path('leave_summary/', views.leave_summary, name='leave_summary'),
    path('leave_dashboard/', views.leave_dashboard, name='leave_dashboard'),

    path('carry-forward-leave/', views.carry_forward_leave, name='carry_forward_leave'),
    path('update_leave_balances_for_all/', views.monthly_leave_accrual_update, name='update_leave_balances_for_all'),
    path('check_and_deduct_late_leaves/', views.check_and_deduct_late_leaves, name='check_and_deduct_late_leaves'),

 

]

myproject/urls.py

from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('select2/', include('django_select2.urls')),
    path('', include('accounts.urls', namespace='accounts')),
    path("accounts/", include("django.contrib.auth.urls")), 
    path('clients/',include('clients.urls',namespace='clients')),  
    path('attendance/',include('attendance.urls',namespace='attendance')),
    path('messaging/',include('messaging.urls',namespace='messaging')),  
    path('payments/',include('payments.urls',namespace='payments')),  
    path('performance/',include('performance.urls',namespace='performance')),  
    path('results/',include('results.urls',namespace='results')),  
    path('school_management/',include('school_management.urls',namespace='school_management')),  
    path('students/',include('students.urls',namespace='students')),  
    path('teachers/',include('teachers.urls',namespace='teachers')),  
    path('core/',include('core.urls',namespace='core')),  
    path('student_portal/',include('student_portal.urls',namespace='student_portal')),  

    path('leavemanagement/',include('leavemanagement.urls',namespace='leavemanagement')),
    path('finance/',include('finance.urls',namespace='finance')),
    path('inventory/',include('inventory.urls',namespace='inventory')),
    path('accounting/',include('accounting.urls',namespace='accounting')),
    path('university_management/',include('university_management.urls',namespace='university_management')),  
    path('varsity_portal/',include('varsity_portal.urls',namespace='varsity_portal')),  

]






if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

leavemanagement/forms.py
from django import forms
from .models import LeaveApplication,LeaveType,AttendanceLog,AttendanceModel,LatePolicy
from datetime import timedelta


import datetime

class AttendancePolicyForm(forms.ModelForm):
    WEEKDAY_CHOICES = [
    ('Monday', 'Monday'),
    ('Tuesday', 'Tuesday'),
    ('Wednesday', 'Wednesday'),
    ('Thursday', 'Thursday'),
    ('Friday', 'Friday'),
    ('Saturday', 'Saturday'),
    ('Sunday', 'Sunday'),
]
    weekened = forms.MultipleChoiceField(
        choices=WEEKDAY_CHOICES,
        widget=forms.CheckboxSelectMultiple,  # Checkboxes for selection
        required=False
    )
   
    class Meta:
        model = LatePolicy
        exclude=['policy_id']
        widgets={
            'max_check_in_time':forms.TimeInput(attrs={'type':'time'}) ,
          
        }
   

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name in self.fields:
            self.fields[field_name].required = False 
            
        if self.instance and self.instance.weekened:
            self.fields['weekened'].initial = self.instance.get_weekends_list()

    def clean_weekened(self):
        """Convert selected weekdays into a comma-separated string before saving."""
        return ','.join(self.cleaned_data['weekened'])
     
       

 
        





class AttendanceForm(forms.ModelForm):
    class Meta:
        model = AttendanceModel
        exclude=['total_hours','user']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)      
        self.fields['date'].widget = forms.DateInput(attrs={'type':'date'})   
        self.fields['check_in_time'].widget = forms.TimeInput(attrs={'type':'time'})   
        self.fields['check_out_time'].widget = forms.TimeInput(attrs={'type':'time'})   
        



class EditAttendanceForm(forms.ModelForm):
    class Meta:
        model = AttendanceModel
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)      
        self.fields['date'].widget = forms.DateInput(attrs={'type':'date'})   
        self.fields['check_in_time'].widget = forms.TimeInput(attrs={'type':'time'})   
        self.fields['check_out_time'].widget = forms.TimeInput(attrs={'type':'time'})   
        
class LeaveTypeForm(forms.ModelForm):
    class Meta:
        model = LeaveType
        exclude=['accrual_rate']

        widgets = {           
        'description':forms.Textarea(attrs={
            'class':'form-control',
            'row':2,
            'style':'height:50px'
        })
        }


class LeaveApplicationForm(forms.ModelForm):
    class Meta:
        model = LeaveApplication
        fields = ['leave_type', 'applied_start_date', 'applied_end_date', 'applied_reason', 'attachment']
        widgets = {
            'applied_start_date': forms.DateInput(attrs={'type': 'date'}),
            'applied_end_date': forms.DateInput(attrs={'type': 'date'}),
            'applied_reason':forms.Textarea(attrs={
                'class':'form-control',
                'row':2,
                'style':'height:50px'
            })
        }


class ApprovalForm(forms.ModelForm):
    class Meta:
        model = LeaveApplication
        fields = ['leave_type', 'approved_start_date', 'approved_end_date','status','rejection_reason']
        widgets = {
            'approved_start_date': forms.DateInput(attrs={'type': 'date'}),
            'approved_end_date': forms.DateInput(attrs={'type': 'date'}),
            'rejection_reason':forms.Textarea(attrs={
                'class':'form-control',
                'row':2,
                'style':'height:50px'
            })
        }


from.models import Shift
class ShiftForm(forms.ModelForm):
    class Meta:
        model=Shift
        fields='__all__'
        widgets={
            'start_time':forms.TimeInput(attrs={'type':'time'}),
            'end_time':forms.TimeInput(attrs={'type':'time'})
        }

templates/leavemanagement/apply_leave.html


{% extends 'base.html' %}

{% block content %}
  
    <div class="container-fluid main-content mb-5">
        <div class="row">
            <div class="col-12 col-md-2"></div>
            <div class="col-12 col-md-6">
                <div class="card shadow-lg border-0 rounded-lg">
                    <div class="card-header bg-primary text-white text-center">
                        <h3 class="mb-0"> Apply Leave</h3>
                    </div>
                      <div class="card-body">                      
                          <form method="POST" enctype="multipart/form-data" class="ms-4">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <div class="d-grid">
                                <button type="submit" class="btn btn-success my-2">Submit Application</button>
                                <a href="{% url 'leavemanagement:pending_leave_list' %}" class="btn btn-secondary">Cancel</a>
                            </div> 
                        </form>
                </div>
            </div>
        </div>

        <div class="col-12 col-md-2"></div>

    </div>
    <h4 style="height:50px"></h4>
</div>

<div style="height:20px"></div>



{% endblock %}

templates/leavemanagement/approve_leave.html

{% extends 'base.html' %}

{% block content %}
  
    <div class="container-fluid main-content mb-5">
        <div class="row">
            <div class="col-12 col-md-2"></div>
            <div class="col-12 col-md-6">
                <div class="card shadow-lg border-0 rounded-lg">
                    <div class="card-header bg-primary text-white text-center">
                        <h3 class="mb-0"> Leave approval</h3>
                    </div>
                      <div class="card-body">
                        <h4 class="text-center">Approve Leave Application</h4>
                        <p class="ms-4">Employee: {{ leave_application.employee }}<br>
                        Leave Type: {{ leave_application.leave_type.name }}<br>
                        Applied Start Date: {{ leave_application.applied_start_date }}<br>
                        Applied End Date: {{ leave_application.applied_end_date }}<br>
                        Applied Days:{{leave_application.applied_no_of_days}} days</p>
                        
                        <form method="POST" class="ms-4 mt-5">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <div class="d-grid">
                                <button type="submit" name="entity_submit"class="btn btn-primary my-2"> Approve</button>
                                <a href="{% url 'leavemanagement:pending_leave_list' %}" class="btn btn-secondary">Cancel</a>
                            </div> 
                        </form>
                </div>
            </div>
        </div>

        <div class="col-12 col-md-2"></div>

    </div>
    <h4 style="height:50px"></h4>
</div>

<div style="height:20px"></div>





<script>
    $(document).ready(function () {
     function toggleFields() {
         var entityType = $('#id_status').val();
 
         if (entityType === 'APPROVED' || entityType === 'PENDING') {
                $('#id_rejection_reason').closest('p').hide();
            } else {
                $('#id_rejection_reason').closest('p').show();
            }
         }
 
     toggleFields(); // Initial call
     $('#id_status').change(function () {
         toggleFields(); // Update fields on change
     });
 });
 
 </script>

{% endblock %}

templates/leavemanagement/leave_history.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block content %}
   

<div class="container-fluid main-content mb-4">
    <div class="row">
        <div class="col-12 col-md-4">

            <h3>Leave Summary:</h3>
            <table class="table table-hover">
                <thead class="table-dark">
                    <tr>
                        <th>Leave Type</th>
                        <th>Total Leave</th>
                        <th>Availed Leave</th>                    
                        <th>Available Leave</th>
                        <th>Carry Forward</th>
                    </tr>
                </thead>
                <tbody>
                    {% for summary in leave_summary %}
                        <tr>
                            <td>{{ summary.leave_type }}</td>
                            <td>{{ summary.total_leave }}</td>
                            <td>{{ summary.approved_leave }}</td>                        
                            <td>{{ summary.available_leave }}</td>
                            <td>{{ summary.carry_forward }}</td>
                        </tr>
                        {% empty %}
                        <tr>
                            <td colspan="5">No leave applications found.</td>
                        </tr>
                        {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-12 col-md-8">

            <h3>Leave Application History:<a href="{% url 'leavemanagement:apply_leave' %}">Apply for leave</a></h3>
            <table class="table table-hover">
                <thead class="table-dark">
                    <tr>
                        <th>Leave Type</th>
                        <th>Start Date</th>
                        <th>End Date</th>
                        <th>No.of Days</th>                        
                        <th>Reasons</th>
                        <th>Attachment</th>
                        <th>Status</th>
                        <th>Rejection reason if any</th>
                    </tr>
                </thead>
                <tbody>
                    {% for application in leave_applications %}
                        <tr>
                            <td>{{ application.leave_type.name }}</td>
                            <td>{{ application.applied_start_date }}</td>
                            <td>{{ application.applied_end_date }}</td>
                            <td>{{ application.applied_no_of_days }}</td>
        
                            <td>{{ application.applied_reason }}</td>
                            <td>                               
                                {% if application.attachment %}
                                    {% if application.attachment.url|is_pdf %}
                                        <a href="{{ application.attachment.url }}" target="_blank">View PDF</a>
                                    {% elif application.attachment.url|is_image %}
                                        <a href="{{ application.attachment.url }}" target="_blank">
                                            <img src="{{ application.attachment.url }}" style="width:40px;height:40px;border-radius: 50%;">
                                        </a>
                                    {% else %}
                                        <a href="{{ application.attachment.url }}" target="_blank">Download File</a>
                                    {% endif %}
                                {% else %}
                                    <strong>No attachment</strong>
                                {% endif %}
                            </td>
                                    
                            <td>
                                {% if application.status == 'APPROVED' %}
                                <i class="fas fa-check fw-bold text-success">Approved</i>
                                {% elif application.status == 'REJECTED' %}
                                <i class="fas fa-times fw-bold text-danger">Rejected</i>                           
                                {% else %}
                                <strong style="color:blue">{{application.get_status_display}}</strong>
                                {% endif %}
                            </td>
                                               
                       
                            <td>
                                {% if application.rejection_reason %}
                                {{ application.rejection_reason }}
                                {% else %}
                                No rejection
        
                            </td>
                            {% endif %}
                           
                        </tr>
                    {% empty %}
                        <tr>
                            <td colspan="4">No leave applications found.</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            
        </div>
    </div>
</div>

    

{% endblock %}

templates/leavemanagement/manage_leave_type.html

{% extends "base.html" %}
{% load static %}

{% block content %}


<div class="container-fluid main-content mb-4">
    <div class="row">
        <div class="col-12 col-md-4">
            <div class="card shadow-lg" style="background-color: aliceblue;">
                 <!-- Card Header -->
                 <div class="card-header bg-primary text-white text-center">
                    <h3 class="mb-0"> {% if instance %} Update leave {% else %} Create leave type {% endif %}</h3>
                </div>              
                <form method="POST" enctype="multipart/form-data" class="p-2 m-4">
                    {% csrf_token %}
                    {{ form.as_p }}   
                    <div class="d-grid">
                        <button type="submit" class="btn btn-primary btn-lg"> {% if instance %} Update {% else %} Add {% endif %}</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-12 col-md-8">
            <table class="table table-hover">
                <thead class="table-dark">
                    <tr>

                        <th>Leave name</th>
                        <th>Description</th>
                        <th>Annual allowance</th>
                        <th>Is carry forwardable?</th> 
                        <th>Max carry forward limit</th> 
                        <th>Is month accruable ?</th>                                    
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for data in page_obj %}
                        <tr>

                            
                            <td>{{ data.name }}</td>                                                                               
                            <td>{{data.description}}</td>
                            <td>{{data.annual_allowance}}</td>
                            <td>
                                {% if data.allow_carry_forward %}
                                Yes{% else %} No {% endif %}
                            </td>                                                                               
                            <td>{{data.max_carry_forward_limit }}</td>
                            <td>
                                {% if data.accrues_monthly %}
                                Yes{% else %} No {% endif %}
                            </td>       
                                                       
                                                      
                            <td class="text-center">
                                <a href="{% url 'leavemanagement:create_leave_type' %}" class="btn btn-sm btn-info">Create</a>
                                <a href="{% url 'leavemanagement:update_leave_type' data.id %}" class="btn btn-sm btn-info">Edit</a>
                               
                                <a href="#" 
                                    class="btn btn-danger btn-sm" 
                                    data-bs-toggle="modal" 
                                    data-bs-target="#deleteModal" 
                                    data-id="{{ data.id }}" 
                                    data-name="{{ data.name }}">
                                        Delete
                                    </a>
                               
                            </td>
                        </tr>
                        {% empty %}
                        <tr>
                            <td colspan="6" class="text-center">No records available.</td>
                        </tr>
                    {% endfor %}
                </tbody>
                
            </table>
                    
            <!-- Pagination Controls -->
            <div class="pagination">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                        <a href="?page=1">&laquo; first</a>
                        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}

                    <span class="current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>

                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">next</a>
                        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                    {% endif %}
                </span>
            </div>


             <!-- Delete Confirmation Modal -->
             <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="deleteModalLabel">Confirm Delete</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            Are you sure you want to delete the transport record: <strong id="modal-entity-name"></strong>?
                        </div>
                        <div class="modal-footer">
                            <form method="post" id="delete-form">
                                {% csrf_token %}
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                                <button type="submit" class="btn btn-danger">Yes, Delete</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <h4 style="height:10px"></h4>
    
</div>

<div style="height:1400px"></div>


<script>
    const deleteModal = document.getElementById('deleteModal');
    deleteModal.addEventListener('show.bs.modal', function (event) {
        const button = event.relatedTarget; 
        const entityId = button.getAttribute('data-id');
        const entityName = button.getAttribute('data-name');

          const modalEntityName = deleteModal.querySelector('#modal-entity-name');
        modalEntityName.textContent = entityName;
  
        const deleteForm = deleteModal.querySelector('#delete-form');
        deleteForm.action = `/leavemanagement/delete_leave_type/${entityId}/`;
    });
</script>




{% endblock %}

templates/leavemanagement/pending_leave_list.html
{% extends 'base.html' %}

{% block content %}

<div class="container-fluid main-content">
    <h4 class="text-center">{% if user.is_authenticated %}
        <a href="{% url 'leavemanagement:carry_forward_leave' %}" class="btn btn-primary">
            Run in January every year for carry forward
        </a>
    {% endif %}

        {% if user.is_authenticated %}
            <a href="{% url 'leavemanagement:update_leave_balances_for_all' %}" class="btn btn-primary">
            Run once at every month to update all accrued leaves
            </a>
        {% endif %}

        {% if user.is_authenticated %}
        <a href="{% url 'leavemanagement:check_and_deduct_late_leaves' %}" class="btn btn-primary">
        Run every day
        </a>
    {% endif %}</h4>

      

    <h3>Pending Leave Applications:</h3>


    {% if pending_with_balance %}
        <table class="table table-hover table-striped mt-3">
            <thead class="table-dark">
                <tr>
                    <th>Employee</th>
                    <th>Leave Type</th>
                    <th>Start Date</th>
                    <th>End Date</th>

                    <th>Days Requested</th>
                    <th>Days Available</th>
                    <th>Status</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
               
                {% for data in pending_with_balance %}
                    <tr>
                        <td>{{ data.application.employee.name }}</td>
                        <td>{{ data.application.leave_type.name }}</td>
                        <td>{{ data.application.applied_start_date }}</td>
                        <td>{{ data.application.applied_end_date }}</td>

                        <td>{{ data.application.applied_no_of_days }}</td>
                        <td>{{ data.allowed_balance }}</td>
                        <td><span class="badge bg-warning">{{ data.application.status }}</span></td>
                        <td>
                           <a href="{% url 'leavemanagement:approve_leave'  data.application.id %}">Approve</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div class="alert alert-info">No pending leave applications.</div>
    {% endif %}
</div>
{% endblock %}