core/urls.py

from django.urls import path
from .import views


app_name = 'core'


urlpatterns = [
    path('staff_operations_dashboard/', views.staff_operations_dashboard, name='staff_operations_dashboard'),
    path('home/', views.home, name='home'),
    path('', views.dashboard, name='dashboard'),
    path('core_dashboard/', views.core_dashboard, name='core_dashboard'),
    path('only_core_dashboard/', views.only_core_dashboard, name='only_core_dashboard'),
    path('view_employee/', views.view_employee, name='view_employee'),
    path('employee_list/', views.employee_list, name='employee_list'),
   
    path('manage_department/', views.manage_department, name='manage_department'),  
    path('manage_location/', views.manage_location, name='manage_location'),

    path('create_positionn/', views.manage_position, name='create_position'),    
    path('update_positionn/<int:id>/', views.manage_position, name='update_position'),    
    path('delete_position/<int:id>/', views.delete_position, name='delete_position'),  
    path('position_details/<int:id>/', views.position_details, name='position_details'),  

    path('create_job_requirement/', views.manage_job_requirement, name='create_job_requirement'),    
    path('update_job_requirement/<int:id>/', views.manage_job_requirement, name='update_job_requirement'),    
    path('delete_job_requirement/<int:id>/', views.delete_job_requirement, name='delete_job_requirement'),  

    path('create_job_description/', views.manage_job_description, name='create_job_description'),    
    path('update_job_description/<int:id>/', views.manage_job_description, name='update_job_description'),    
    path('delete_job_description/<int:id>/', views.delete_job_descriptiont, name='delete_job_description'),  

    path('create_company/', views.create_company, name='create_company'),
    path('update_company/<int:id>/', views.create_company, name='update_company'),
    path('delete_company/<int:id>/', views.delete_company,  name='delete_company'),    
    
    path('manage_employee/', views.manage_employee, name='manage_employee'),
    path('update_employee/<int:id>/', views.manage_employee, name='update_employee'),
    path('delete_employee/<int:id>/', views.delete_employee,  name='delete_employee'),    

    path('manage_doctor/', views.manage_doctor, name='manage_doctor'),
    path('update_doctor/<int:id>/', views.manage_doctor, name='update_doctor'),
    path('delete_doctor/<int:id>/', views.delete_doctor,  name='delete_doctor'),   

    path('manage_nurse/', views.manage_nurse, name='manage_nurse'),
    path('update_nurse/<int:id>/', views.manage_nurse, name='update_nurse'),
    path('delete_nurse/<int:id>/', views.delete_nurse,  name='delete_nurse'),   
            
    path('add_notice/', views.add_notice, name='add_notice'), 
    path('view_notices/', views.view_notices, name='view_notices'),  
    path('all_qc/', views.all_qc, name='all_qc'),
        
    path('create_salary/', views.create_salary, name='create_salary'),
    path('download_salary/', views.download_salary, name='download_salary'),

    path('view_employee_changes/', views.view_employee_changes, name='view_employee_changes'),
    path('download_employee_changes/', views.download_employee_changes, name='download_employee_changes'),

    path('view_employee_changes_single/<int:employee_id>/', views.view_employee_changes_single, name='view_employee_changes_single'),
    
    path('preview_pay_slip/<int:employee_id>/', views.preview_pay_slip, name='preview_pay_slip'),
    path('generate_and_send_pay_slip/<int:employee_id>/', views.generate_and_send_pay_slip, name='generate_and_send_pay_slip'),
        
    path('preview_salary_certificate/<int:employee_id>/', views.preview_salary_certificate, name='preview_salary_certificate'),
    path('generate_and_send_salary_certificate/<int:employee_id>/', views.generate_and_send_salary_certificate, name='generate_and_send_salary_certificate'),
          
    path('preview_experience_certificate/<int:employee_id>/', views.preview_experience_certificate, name='preview_experience_certificate'),
    path('generate_and_send_experience_certificate/<int:employee_id>/', views.generate_and_send_experience_certificate, name='generate_and_send_experience_certificate'),
      
    path('create_company_policy/', views.manage_company_policy, name='create_company_policy'),
    path('update_company_policy/<int:id>/', views.manage_company_policy, name='update_company_policy'),
    path('delete_company_policy/<int:id>/', views.delete_company_policy, name='delete_company_policy'),   

    path('create_salary_structure/', views.manage_salary_structure, name='create_salary_structure'),
    path('update_salary_structure/<int:id>/', views.manage_salary_structure, name='update_salary_structure'),
    path('delete_salary_structure/<int:id>/', views.delete_salary_structure, name='delete_salary_structure'),   
    
    path('create_festival/', views.manage_festival, name='create_festival'),
    path('update_festival/<int:id>/', views.manage_festival, name='update_festival'),
    path('delete_festival/<int:id>/', views.delete_festival, name='delete_festival'),   

    path('create_performance_bonus/', views.manage_performance_bonus, name='create_performance_bonus'),
    path('update_performance_bonus/<int:id>/', views.manage_performance_bonus, name='update_performance_bonus'),
    path('delete_performance_bonus/<int:id>/', views.delete_performance_bonus, name='delete_performance_bonus'),   


]

myproject/urls.py

from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('select2/', include('django_select2.urls')),
    path('', include('accounts.urls', namespace='accounts')),
    path("accounts/", include("django.contrib.auth.urls")), 
    path('clients/',include('clients.urls',namespace='clients')),  
    path('attendance/',include('attendance.urls',namespace='attendance')),
    path('messaging/',include('messaging.urls',namespace='messaging')),  
    path('payments/',include('payments.urls',namespace='payments')),  
    path('performance/',include('performance.urls',namespace='performance')),  
    path('results/',include('results.urls',namespace='results')),  
    path('school_management/',include('school_management.urls',namespace='school_management')),  
    path('students/',include('students.urls',namespace='students')),  
    path('teachers/',include('teachers.urls',namespace='teachers')),  
    path('core/',include('core.urls',namespace='core')),  
    path('student_portal/',include('student_portal.urls',namespace='student_portal')),  

    path('leavemanagement/',include('leavemanagement.urls',namespace='leavemanagement')),
    path('finance/',include('finance.urls',namespace='finance')),
    path('inventory/',include('inventory.urls',namespace='inventory')),
    path('accounting/',include('accounting.urls',namespace='accounting')),
    path('university_management/',include('university_management.urls',namespace='university_management')),  
    path('varsity_portal/',include('varsity_portal.urls',namespace='varsity_portal')),  

]






if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

students/urls.py

from . import views
from django.urls import path
from django.contrib.auth import views as auth_views
 
from clients.views import tenant_expire_check




app_name = 'students'

urlpatterns = [
    path('', tenant_expire_check, name='tenant_expire_check'),   

    path('create_guardian/', views.manage_guardian, name='create_guardian'),    
    path('update_guardian/<int:id>/', views.manage_guardian, name='update_guardian'),    
    path('delete_guardian/<int:id>/', views.delete_guardian, name='delete_guardian'),  

    path('create_student/', views.manage_student, name='create_student'),    
    path('update_student/<int:id>/', views.manage_student, name='update_student'),    
    path('delete_student/<int:id>/', views.delete_student, name='delete_student'),  

    path('create_student_enrollment/', views.manage_student_enrollment, name='create_student_enrollment'),    
    path('update_student_enrollment/<int:id>/', views.manage_student_enrollment, name='update_student_enrollment'),    
    path('delete_student_enrollment/<int:id>/', views.delete_student_enrollment, name='delete_student_enrollment'), 

    path('get-subjects/', views.get_subjects, name='get_subjects'),
    path('enroll_student/', views.enroll_student, name='enroll_student'),
     path('get_enrollments/<int:student_id>/', views.get_student_enrollments, name='get_student_enrollments'),
     path('get_student_data/<int:student_id>/', views.get_student_related_data, name='get_student_data'),

    path('view_student_vcard/', views.view_student_vcard, name='view_student_vcard'),
    path('student-details/<str:student_id>/', views.get_student_details, name='student-details'),

    path('student_exam_schedule/<int:student_id>/', views.student_exam_schedule, name='student_exam_schedule'),
     path('exam_schedule_view/', views.exam_schedule_view, name='exam_schedule_view'),
    path('preview_admit_card/<int:exam_id>/', views.preview_admit_card, name='preview_admit_card'),
    
    path('student_weekly_schedule/', views.student_weekly_schedule, name='student_weekly_schedule'),
    path('student_weekly_schedule_with_id<int:student_id>/', views.student_weekly_schedule_with_id, name='student_weekly_schedule_with_id'),
    path('view_student_weekly_schedule/', views.view_student_weekly_schedule, name='view_student_weekly_schedule'),


    path('exam-fees/<int:pk>/edit/', views.ExamFeeUpdateView.as_view(), name='exam_fee_edit'),
    path('exam-fees/<int:pk>/delete/', views.ExamFeeDeleteView.as_view(), name='exam_fee_delete'),

    path('transport-routes/', views.TransportRouteListView.as_view(), name='transport_route_list'),
    path('transport-routes/add/', views.TransportRouteCreateView.as_view(), name='transport_route_add'),
    path('transport-routes/<int:pk>/edit/', views.TransportRouteUpdateView.as_view(), name='transport_route_edit'),
    path('transport-routes/<int:pk>/delete/', views.TransportRouteDeleteView.as_view(), name='transport_route_delete'),
    
    path('transport-assignment-list/', views.TransportAssignmentListView.as_view(), name='transport_assignment_list'),
    path('transport-assignment/add/', views.TransportAssignmentCreateView.as_view(), name='transport_assignment_add'),
    path('transport-assignment/<int:pk>/edit/', views.TransportAssignmentUpdateView.as_view(), name='transport_assignment_edit'),
    path('transport-assignment/<int:pk>/delete/', views.TransportAssignmentDeleteView.as_view(), name='transport_assignment_delete'),

    path('hostel_room_type_list/', views.HostelRoomTypeListView.as_view(), name='hostel_room_type_list'),
    path('hostel_room_type_/add/', views.HostelRoomTypeCreateView.as_view(), name='hostel_room_type_add'),
    path('hostel_room_type_/<int:pk>/edit/', views.HostelRoomTypeUpdateView.as_view(), name='hostel_room_type_edit'),
    path('hostel_room_type_/<int:pk>/delete/', views.HostelRoomTypeDeleteView.as_view(), name='hostel_room_type_delete'),

    path('hostel_list/', views.HostelListView.as_view(), name='hostel_list'),
    path('hostel/add/', views.HostelCreateView.as_view(), name='hostel_add'),
    path('hostel/<int:pk>/edit/', views.HostelUpdateView.as_view(), name='hostel_edit'),
    path('hostel/<int:pk>/delete/', views.HostelDeleteView.as_view(), name='hostel_delete'),

    path('hostel_room_list/', views.HostelRoomlListView.as_view(), name='hostel_room_list'),  
    path('hostel_room_/add/', views.HostelRoomCreateView.as_view(), name='hostel_room_add'),
    path('hoste_rooml/<int:pk>/edit/', views.HostelRoomUpdateView.as_view(), name='hostel_room_edit'),
    path('hostel_room/<int:pk>/delete/', views.HostelRoomlDeleteView.as_view(), name='hostel_room_delete'),


    path('hostel_assignment_list/', views.HostelAssignmentlListView.as_view(), name='hostel_assignment_list'),  
    path('hostel_assignment_/add/', views.HostelAssignmentCreateView.as_view(), name='hostel_assignment_add'),
    path('hoste_assignment/<int:pk>/edit/', views.HostelAssignmentUpdateView.as_view(), name='hostel_assignment_edit'),
    path('hostel_assignment/<int:pk>/delete/', views.HostelAssignmentDeleteView.as_view(), name='hostel_assignment_delete'),
 
    path('assign_other_fee_by_class/', views.assign_other_fee_by_class, name='assign_other_fee_by_class'), 
    path('other_fees_list/', views.OtherFeesListView.as_view(), name='other_fees_list'),  
    path('other_fees__/add/', views.OtherFeesCreateView.as_view(), name='other_fees_add'),
    path('other_fees_/<int:pk>/edit/', views.OtherFeesUpdateView.as_view(), name='other_fees_edit'),
    path('other_fees_/<int:pk>/delete/', views.OtherFeesDeleteView.as_view(), name='other_fees_delete'),


    path('tuition_assignment_list/', views.TuitionAssignmentListView.as_view(), name='tuition_assignment_list'),  
    path('tuition_assignment_/add/', views.TuitionAssignmentCreateView.as_view(), name='tuition_assignment_add'),
    path('tuition_assignment/<int:pk>/edit/', views.TuitionAssignmentUpdateView.as_view(), name='tuition_assignment_edit'),
    path('tuition_assignment/<int:pk>/delete/', views.TuitionAssignmentCreateView.as_view(), name='tuition_assignment_delete'),

    path('admission_assignment_list/', views.AdmissionAssignmentListView.as_view(), name='admission_assignment_list'),  
    path('admission_assignment_/add/', views.AdmissionAssignmentCreateView.as_view(), name='admission_assignment_add'),
    path('admission_assignment/<int:pk>/edit/', views.AdmissionAssignmentUpdateView.as_view(), name='admission_assignment_edit'),
    path('admission_assignment/<int:pk>/delete/', views.AdmissionAssignmentDeleteView.as_view(), name='admission_assignment_delete'),
     
    path('student_dues_overview/', views.student_dues_overview, name='student_dues_overview'),   
    path('student_id_card_view/<int:student_id>/', views.student_id_card_view, name='student_id_card_view'),
    path('download_student_id_card/<int:student_id>/', views.download_student_id_card, name='download_student_id_card'),
    path('student_subject_enrollment_view/<int:student_id>/', views.student_subject_enrollment_view, name='student_subject_enrollment_view'),  
    path('student_id_card_print/', views.student_id_card_print, name='student_id_card_print'),

     path('student_school_class_routine_view/', views.school_class_routine_view, name='student_school_class_routine_view'),  



] 



varsity_portal/urls.py
from django.urls import path
from .views import *

app_name = 'varsity_portal'

urlpatterns = [  
   
    path('student_enrollment/create/', StudentEnrollmentCreateView.as_view(), name='student_enrollment_create'),
    path('student_enrollment', student_enrollment, name='student_enrollment'),
    path('enrollment_list/', student_enrollment_list, name='enrollment_list'),
    path('create_term_registration/', term_registration_create, name='create_term_registration'),
    path('term-registration-detail/',student_term_registration_detail,name='term_registration_detail'),
    path('get_subjects_for_term/',get_subjects_for_term,name='get_subjects_for_term'),
    path('get_terms_for_level/',get_terms_for_level,name='get_terms_for_level'),

    path('invoices/', student_invoices_list, name='student_invoices_list'),
    path('invoices/<int:invoice_id>/', student_invoice_detail, name='student_invoice_detail'),
   
    path('payment-list/', university_payment_list, name='payment_list'),
    path('exams/', ExamListView.as_view(), name='exam_list'),  
    path('exams/<int:pk>/', ExamDetailView.as_view(), name='exam_detail'), 

   path('term_list/',term_list,name='term_list'),
   path('class_schedule_view/<int:term_id>/',class_schedule_view,name='class_schedule_view'),
   path('student_class_schedule_view/<int:term_id>/',student_class_schedule,name='student_class_schedule'),
   path('student_class_schedule_calendar/<int:term_id>/',student_class_schedule_calendar,name='student_class_schedule_calendar'),

    path('register_for_exam/<int:exam_id>/',register_for_exam,name='register_for_exam'),
    path('generate_admit_card/<int:registration_id>/',generate_admit_card,name='generate_admit_card'),
    path('student_transcript/',student_transcript,name='student_transcript'),

    path('common_dashboard/',common_dashboard,name='common_dashboard'),
    path('view_student_vcard/', view_student_vcard,name='view_student_vcard'),
    path('student_landing_page/', student_landing_page,name='student_landing_page'),



]

varsity_portal/models.py
from django.db import models

# Create your models here.

templates/varsity_portal/common_dashboard.html

{% extends "student_portal_base.html" %}
{% load static %}

{% block content %}


<style>
     /* ---------- Header ---------- */
    .header {
        text-align: center;
        border-bottom: 2px solid #000;
        padding-bottom: 10px;
        margin-bottom: 20px;
    }

    .header h1 {
        font-size: 22px;
        margin: 0;
        letter-spacing: 0.5px;
    }

    .header h2 {
        font-size: 14px;
        font-weight: normal;
        margin: 4px 0 0;
    }

</style>



<!-- Header -->
    <div class="header">
          {% if school.logo %}
                <img src="{{ school.logo.url }}"
                 alt="School Logo" style="width:60px;height:60px">
            {% else %}
                <div style="width:80px;"></div>
            {% endif %}
              
        <p>
             <h1>{{ school.name }}</h1> 
            <strong>Reg.code:{{ school.code }}</strong><br>
            {{ school.address }}<br>
            {{ school.website }}
        </p>
        <h4>Dashboard</h4>
        
    </div>


{% include 'varsity_portal/quick_access_link.html' %}

<div class="container-fluid my-4">

    <!-- Welcome Banner -->
    <div class="card mb-4 shadow-sm">
        <div class="card-body text-center">
            <h3>Welcome, {{ request.user.get_full_name }}</h3>
            <p class="text-muted">Role: {{ request.user.get_role_display }}</p>
        </div>
    </div>

    <!-- Quick Stats -->
    <div class="row g-4 mb-4">
        <div class="col-md-3 col-6">
            <div class="card shadow-sm border-primary text-center p-3">
                <h6 class="text-success">Total Students</h6>
                <h3>{{ total_students }}</h3>
            </div>
        </div>
        <div class="col-md-3 col-6">
            <div class="card shadow-sm border-danger text-center p-3">
                <h6 class="text-danger">Total Programs</h6>
                <h3>{{ total_programs }}</h3>
            </div>
        </div>
         <div class="col-md-3 col-6">
            <div class="card shadow-sm border-primary text-center p-3">
                <h6 class="text-success">Active Sessions</h6>
                <h3>{{ total_active_sessions }}</h3>
            </div>
        </div>
         <div class="col-md-3 col-6">
            <div class="card shadow-sm border-success text-center p-3">
                <h6 class="text-primary">Total Terms</h6>
                <h3>{{ total_terms }}</h3>
            </div>
        </div>
    </div>

    <!-- Finance Overview (only for admin/finance) -->
    {% if request.user.role in 'admin,finance' %}
    <div class="row g-4 mb-4">
         <div class="col-md-4 col-6">
            <div class="card shadow-sm border-danger text-center p-3">
                <h6 class="text-danger">Total Revenue</h6>
                <h3>৳ {{ total_revenue|floatformat:2 }}</h3>
            </div>
        </div>
          <div class="col-md-4 col-6">
            <div class="card shadow-sm text-center p-3">
                <h6>Total Due</h6>
                <h3>৳ {{ total_due|floatformat:2 }}</h3>
            </div>
        </div>
    </div>
    {% endif %}

    <!-- Teacher Assigned Subjects -->
    {% if teacher_subjects %}
    <a href="{% url 'university_management:term_list' %}"
    class="btn btn-sm btn-outline-primary">Class schedule</a>
    <div class="card shadow-sm mb-4">
        <div class="card-body">
            <h5 class="fw-semibold mb-3">Your Assigned Subjects</h5>
            <ul class="list-group list-group-flush">
                {% for subject in teacher_subjects %}
                <li class="list-group-item">
                    {{ subject.subject_offering.program }} -- {{ subject.subject_offering.subject.name }} -- {{ subject.subject_offering.term }} 
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    {% endif %}

   
</div>
{% endblock %}

templates/varsity_portal/quick_access_link.html

<div class="container my-3 no-print">

    <h5 class="text-center mb-3 fw-bold">Quick Navigation</h5>

    <div class="d-flex justify-content-center flex-wrap gap-2">

        <!-- Primary Actions -->
        <a href="{% url 'varsity_portal:student_enrollment' %}" class="btn btn-primary btn-sm shadow-sm">
            <i class="bi bi-person-plus-fill"></i> Student Enrollment
        </a>
        <a href="{% url 'varsity_portal:enrollment_list' %}" class="btn btn-warning btn-sm shadow-sm">
            <i class="bi bi-list-ul"></i> Enrollment List
        </a>
        <a href="{% url 'varsity_portal:student_invoices_list' %}" class="btn btn-secondary btn-sm shadow-sm">
            <i class="bi bi-receipt"></i> Student Invoices
        </a>

        <!-- Class/Term -->
       
        <a href="{% url 'varsity_portal:payment_list' %}" class="btn btn-info btn-sm shadow-sm">
            <i class="bi bi-cash-stack"></i> Payment List
        </a>

        <!-- Exam -->
        <a href="{% url 'varsity_portal:term_list' %}" class="btn btn-primary btn-sm shadow-sm">
            <i class="bi bi-journal-plus"></i> Class Routine
        </a>
        <a href="{% url 'varsity_portal:exam_list' %}" class="btn btn-secondary btn-sm shadow-sm">
            <i class="bi bi-journal-text"></i> Exam List
        </a>

         <a href="{% url 'varsity_portal:common_dashboard' %}" class="btn btn-success btn-sm shadow-sm">
            <i class="bi bi-journal-text"></i> Dashboard
        </a>
      
    </div>

</div>

<!-- Optional: small custom CSS for hover & spacing -->
<style>
    .btn-sm {
        min-width: 150px;
        text-align: center;
        font-size: 0.85rem;
    }

    .btn-sm i {
        margin-right: 5px;
    }

    .btn-sm:hover {
        transform: translateY(-2px);
        transition: 0.2s;
    }
</style>

templates/varsity_portal/student_data.html
<style>
    .info-box {
        border: 1px solid #e0e0e0;
        border-radius: 12px;
        background: #ffffff;
        padding: 15px;
        box-shadow: 0 4px 10px rgba(0,0,0,0.05);
        font-size: 14px;
        min-height: 260px;
    }

    .info-title {
        font-weight: 600;
        color: #007bff;
        margin-bottom: 8px;
        font-size: 15px;
        text-transform: uppercase;
    }

    .encircle-card {
        border: 3px solid #007bff;
        border-radius: 20px;
        padding: 15px;
        background-color: #f8f9fa;
        box-shadow: 0 6px 15px rgba(0,0,0,0.15);
    }
</style>

<div class="center-container">

    <div class="text-center mb-4 border-bottom pb-2">
        {% if student.school.logo %}
            <img src="{{ student.school.logo.url }}" style="height:70px; width:auto;" class="mb-2">
        {% endif %}
        <h3 class="mb-0 fw-bold">{{ student.school.name }}</h3>
        <p class="mb-0">{{ student.school.address }}</p>
        {% if student.school.website %}
            <p class="mb-0">{{ student.school.website }}</p>
        {% endif %}
    </div>

    <div class="row justify-content-center mt-4">

        <!-- LEFT PANEL -->
        <div class="col-12 col-md-3 mb-4">
            <div class="info-box">
                <div class="info-title">Guardian Info</div>
                Father: {{ student.guardian.name }}<br>
                Contact: {{ student.guardian.phone_number }}<br><br>

                <div class="info-title">Program Details</div>
                Language: {{ student.varsity_student_enrollments.first.language.name}}<br>
                Roll: {{ student.varsity_student_enrollments.first.roll_number }}<br>
                Student Session: {{ student.varsity_student_enrollments.first.academic_session }}<br>
                Program: {{ student.varsity_student_enrollments.first.program.name }}
            </div>
        </div>

        <!-- PROFILE CENTER -->
        <div class="col-12 col-md-4 mb-4">
            <div class="encircle-card">
                <div class="card shadow-lg border-0">

                    <div class="d-flex justify-content-center mt-3">
                        {% if student.profile_picture %}
                            <img src="{{ student.profile_picture.url }}" 
                                 class="rounded-circle border"
                                 style="width:70px; height:70px; object-fit:cover; border:2px solid #007bff;">
                        {% endif %}
                    </div>

                    <div class="card-body text-center">
                        <h5 class="fw-bold mb-1">{{ student.name }}</h5>
                        <p class="text-muted mb-2">
                            ID: {{ student.student_id }}<br>
                            {{ student.enrolled_students.first.academic_class.name }} /
                            {{ student.enrolled_students.first.shift.name }} /
                            {{ student.enrolled_students.first.section.name }}
                        </p>

                        <div class="d-grid gap-2">
                          
                                <a href="{% url 'varsity_portal:exam_list' %}" class="btn btn-sm btn-outline-success">Exam & admit card</a>
                                <a href="{% url 'students:student_id_card_view' student.id %}" class="btn btn-sm btn-outline-success">ID Card</a>
                                <a href="{% url 'varsity_portal:term_registration_detail' %}" class="btn btn-sm btn-outline-success">Subjects</a>
                                <a href="{% url 'varsity_portal:term_list' %}" class="btn btn-sm btn-outline-success">Class Routine</a>
                                 <a href="{% url 'varsity_portal:student_transcript' %}" class="btn btn-sm btn-outline-primary">Transcript</a>
                                 <a href="{% url 'varsity_portal:student_invoices_list' %}" class="btn btn-sm btn-outline-primary">Dues</a>
                                 
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- RIGHT PANEL -->
        <div class="col-12 col-md-3 mb-4">
            <div class="info-box">
                <div class="info-title">Performance</div>
               {% for result in student_term_gpa %}
               
                    <div class="card mb-2">
                        <div class="card-body">
                            <h5 class="card-title">{{ result.level }}-{{ result.term.name }}-GPA:{{ result.gpa }}</h5>
                        </div>
                    </div>
                    {% endfor %}

                     <div class="card mb-2" style="border:1px solid green">
                        <div class="card-body">                          
                           <p class="text-center"> CGPA:<strong>{{ student_cgpa.cgpa }}</strong><br>
                           
                            </p>
                        </div>
                    </div>


              
                Attendance (Current month): 94%<br><br>

                <div class="info-title">Upcoming Exams</div>
               <p>{% for exam in upcoming_exams %}
               {{ exam.level.title }}-{{ exam.term.name }}-exam date:{{exam.start_date}}-{{exam.end_date}}
               {% endfor %}
               </p>

                <div class="info-title mt-2">Fees Status</div>
                {% if has_due %}
                 Status: <span class="text-warning">
                    <a href="{% url 'varsity_portal:student_invoices_list' %}"> Due exist</a>                   
                </span>
                 {% else %}
                Status: <span class=" badge bg-success">Up to Date</span>
                {% endif %}
            </div>
        </div>

    </div>
</div>