core/urls.py

from django.urls import path
from .import views


app_name = 'core'


urlpatterns = [
    path('staff_operations_dashboard/', views.staff_operations_dashboard, name='staff_operations_dashboard'),
    path('home/', views.home, name='home'),
    path('', views.dashboard, name='dashboard'),
    path('core_dashboard/', views.core_dashboard, name='core_dashboard'),
    path('only_core_dashboard/', views.only_core_dashboard, name='only_core_dashboard'),
    path('view_employee/', views.view_employee, name='view_employee'),
    path('employee_list/', views.employee_list, name='employee_list'),
   
    path('manage_department/', views.manage_department, name='manage_department'),  
    path('manage_location/', views.manage_location, name='manage_location'),

    path('create_positionn/', views.manage_position, name='create_position'),    
    path('update_positionn/<int:id>/', views.manage_position, name='update_position'),    
    path('delete_position/<int:id>/', views.delete_position, name='delete_position'),  
    path('position_details/<int:id>/', views.position_details, name='position_details'),  

    path('create_job_requirement/', views.manage_job_requirement, name='create_job_requirement'),    
    path('update_job_requirement/<int:id>/', views.manage_job_requirement, name='update_job_requirement'),    
    path('delete_job_requirement/<int:id>/', views.delete_job_requirement, name='delete_job_requirement'),  

    path('create_job_description/', views.manage_job_description, name='create_job_description'),    
    path('update_job_description/<int:id>/', views.manage_job_description, name='update_job_description'),    
    path('delete_job_description/<int:id>/', views.delete_job_descriptiont, name='delete_job_description'),  

    path('create_company/', views.create_company, name='create_company'),
    path('update_company/<int:id>/', views.create_company, name='update_company'),
    path('delete_company/<int:id>/', views.delete_company,  name='delete_company'),    
    
    path('manage_employee/', views.manage_employee, name='manage_employee'),
    path('update_employee/<int:id>/', views.manage_employee, name='update_employee'),
    path('delete_employee/<int:id>/', views.delete_employee,  name='delete_employee'),    

    path('manage_doctor/', views.manage_doctor, name='manage_doctor'),
    path('update_doctor/<int:id>/', views.manage_doctor, name='update_doctor'),
    path('delete_doctor/<int:id>/', views.delete_doctor,  name='delete_doctor'),   

    path('manage_nurse/', views.manage_nurse, name='manage_nurse'),
    path('update_nurse/<int:id>/', views.manage_nurse, name='update_nurse'),
    path('delete_nurse/<int:id>/', views.delete_nurse,  name='delete_nurse'),   
            
    path('add_notice/', views.add_notice, name='add_notice'), 
    path('view_notices/', views.view_notices, name='view_notices'),  
    path('all_qc/', views.all_qc, name='all_qc'),
        
    path('create_salary/', views.create_salary, name='create_salary'),
    path('download_salary/', views.download_salary, name='download_salary'),

    path('view_employee_changes/', views.view_employee_changes, name='view_employee_changes'),
    path('download_employee_changes/', views.download_employee_changes, name='download_employee_changes'),

    path('view_employee_changes_single/<int:employee_id>/', views.view_employee_changes_single, name='view_employee_changes_single'),
    
    path('preview_pay_slip/<int:employee_id>/', views.preview_pay_slip, name='preview_pay_slip'),
    path('generate_and_send_pay_slip/<int:employee_id>/', views.generate_and_send_pay_slip, name='generate_and_send_pay_slip'),
        
    path('preview_salary_certificate/<int:employee_id>/', views.preview_salary_certificate, name='preview_salary_certificate'),
    path('generate_and_send_salary_certificate/<int:employee_id>/', views.generate_and_send_salary_certificate, name='generate_and_send_salary_certificate'),
          
    path('preview_experience_certificate/<int:employee_id>/', views.preview_experience_certificate, name='preview_experience_certificate'),
    path('generate_and_send_experience_certificate/<int:employee_id>/', views.generate_and_send_experience_certificate, name='generate_and_send_experience_certificate'),
      
    path('create_company_policy/', views.manage_company_policy, name='create_company_policy'),
    path('update_company_policy/<int:id>/', views.manage_company_policy, name='update_company_policy'),
    path('delete_company_policy/<int:id>/', views.delete_company_policy, name='delete_company_policy'),   

    path('create_salary_structure/', views.manage_salary_structure, name='create_salary_structure'),
    path('update_salary_structure/<int:id>/', views.manage_salary_structure, name='update_salary_structure'),
    path('delete_salary_structure/<int:id>/', views.delete_salary_structure, name='delete_salary_structure'),   
    
    path('create_festival/', views.manage_festival, name='create_festival'),
    path('update_festival/<int:id>/', views.manage_festival, name='update_festival'),
    path('delete_festival/<int:id>/', views.delete_festival, name='delete_festival'),   

    path('create_performance_bonus/', views.manage_performance_bonus, name='create_performance_bonus'),
    path('update_performance_bonus/<int:id>/', views.manage_performance_bonus, name='update_performance_bonus'),
    path('delete_performance_bonus/<int:id>/', views.delete_performance_bonus, name='delete_performance_bonus'),   


]

myproject/urls.py

from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('select2/', include('django_select2.urls')),
    path('', include('accounts.urls', namespace='accounts')),
    path("accounts/", include("django.contrib.auth.urls")), 
    path('clients/',include('clients.urls',namespace='clients')),  
    path('attendance/',include('attendance.urls',namespace='attendance')),
    path('messaging/',include('messaging.urls',namespace='messaging')),  
    path('payments/',include('payments.urls',namespace='payments')),  
    path('performance/',include('performance.urls',namespace='performance')),  
    path('results/',include('results.urls',namespace='results')),  
    path('school_management/',include('school_management.urls',namespace='school_management')),  
    path('students/',include('students.urls',namespace='students')),  
    path('teachers/',include('teachers.urls',namespace='teachers')),  
    path('core/',include('core.urls',namespace='core')),  
    path('student_portal/',include('student_portal.urls',namespace='student_portal')),  

    path('leavemanagement/',include('leavemanagement.urls',namespace='leavemanagement')),
    path('finance/',include('finance.urls',namespace='finance')),
    path('inventory/',include('inventory.urls',namespace='inventory')),
    path('accounting/',include('accounting.urls',namespace='accounting')),
    path('university_management/',include('university_management.urls',namespace='university_management')),  
    path('varsity_portal/',include('varsity_portal.urls',namespace='varsity_portal')),  

]






if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

university_management/urls.py
from django.urls import path
from .views import *

app_name = 'university_management'

urlpatterns = [     
   
    path('student_enrollment', student_enrollment, name='student_enrollment'),
    path('enrollment_list/', StudentEnrollmentListView.as_view(), name='enrollment_list'),
    path('create_term_registration/<int:enrollment_id>/', term_registration_create, name='create_term_registration'),
    path('term-registration-detail/<int:student_id>/',student_term_registration_detail,name='term_registration_detail'),
    path('get_subjects_for_term/',get_subjects_for_term,name='get_subjects_for_term'),
    path('get_terms_for_level/',get_terms_for_level,name='get_terms_for_level'),

    path('invoices/', student_invoices_list, name='student_invoices_list'),
    path('invoices/<int:invoice_id>/', student_invoice_detail, name='student_invoice_detail'),
    path('payment/create/<int:invoice_id>/', university_payment_create, name='make_payment'),
    path('payment-list/', university_payment_list, name='payment_list'),

    path('exams/', exam_list, name='exam_list'),
    path('exams/create/', ExamCreateView.as_view(), name='exam_create'),
    path('exams/<int:pk>/', ExamDetailView.as_view(), name='exam_detail'),
    path('exams/<int:pk>/edit/', ExamUpdateView.as_view(), name='exam_update'),
    path('exams/<int:pk>/delete/', ExamDeleteView.as_view(), name='exam_delete'),
    path('exams/<int:exam_id>/schedule/add/', ExamScheduleCreateView.as_view(), name='exam_schedule_add'),
    path('schedule/<int:pk>/edit/', ExamScheduleUpdateView.as_view(), name='exam_schedule_update'),
    path('schedule/<int:pk>/delete/', ExamScheduleDeleteView.as_view(), name='exam_schedule_delete'),
    path('exams/schedule/create/', exam_create_with_schedule, name='exam_schedule_create'),
    path('exams/<int:pk>/publish/',exam_publish_toggle,name='exam_publish_toggle'),

    path('register_for_exam/<int:exam_id>/',register_for_exam,name='register_for_exam'),
    path('generate_admit_card/<int:exam_id>/',generate_admit_card,name='generate_admit_card'),
    path('enter_student_results/<int:exam_id>/',enter_student_results,name='enter_student_results'),
    path('student_transcript/<int:student_id>/',student_transcript,name='student_transcript'),


    path('schedule/terms/',term_list,name='term_list'),
    path('class_schedule_view/<int:term_id>/', schedule_calendar_view,name='class_schedule_view'),
    path('class_schedule_create/<int:term_id>/', class_schedule_create,name='class_schedule_create'),
    # path('student/class-schedule/<int:term_id>/',student_class_schedule,name='student_class_schedule'),
    path('teacher/class-schedule/<int:term_id>?', teacher_class_schedule,name='teacher_class_schedule_view'),

    path('common_dashboard/', common_dashboard,name='common_dashboard'),
    path('revenue_dashboard/', revenue_dashboard,name='revenue_dashboard'),


]

varsity_portal/urls.py
from django.urls import path
from .views import *

app_name = 'varsity_portal'

urlpatterns = [  
   
    path('student_enrollment/create/', StudentEnrollmentCreateView.as_view(), name='student_enrollment_create'),
    path('student_enrollment', student_enrollment, name='student_enrollment'),
    path('enrollment_list/', student_enrollment_list, name='enrollment_list'),
    path('create_term_registration/', term_registration_create, name='create_term_registration'),
    path('term-registration-detail/',student_term_registration_detail,name='term_registration_detail'),
    path('get_subjects_for_term/',get_subjects_for_term,name='get_subjects_for_term'),
    path('get_terms_for_level/',get_terms_for_level,name='get_terms_for_level'),

    path('invoices/', student_invoices_list, name='student_invoices_list'),
    path('invoices/<int:invoice_id>/', student_invoice_detail, name='student_invoice_detail'),
   
    path('payment-list/', university_payment_list, name='payment_list'),
    path('exams/', ExamListView.as_view(), name='exam_list'),  
    path('exams/<int:pk>/', ExamDetailView.as_view(), name='exam_detail'), 

   path('term_list/',term_list,name='term_list'),
   path('class_schedule_view/<int:term_id>/',class_schedule_view,name='class_schedule_view'),
   path('student_class_schedule_view/<int:term_id>/',student_class_schedule,name='student_class_schedule'),
   path('student_class_schedule_calendar/<int:term_id>/',student_class_schedule_calendar,name='student_class_schedule_calendar'),

    path('register_for_exam/<int:exam_id>/',register_for_exam,name='register_for_exam'),
    path('generate_admit_card/<int:registration_id>/',generate_admit_card,name='generate_admit_card'),
    path('student_transcript/',student_transcript,name='student_transcript'),

    path('common_dashboard/',common_dashboard,name='common_dashboard'),
    path('view_student_vcard/', view_student_vcard,name='view_student_vcard'),
    path('student_landing_page/', student_landing_page,name='student_landing_page'),



]

varsity_portal/models.py
from django.db import models

# Create your models here.

templates/varsity_portal/exams/exam_detail.html
{% extends "student_portal_base.html" %}
{% load custom_filters %}



{% block content %}


{% include 'varsity_portal/quick_access_link.html' %}
<div class="container">
    <div class="row">

        <h2>Exam Details</h2>

        <p>
            <strong>Institution:</strong> {{ object.institution }} <br>
            <strong>Academic Session:</strong> {{ object.academic_session }} <br>
             <strong>Academic Year:</strong> {{ object.academic_year }} <br>
            <strong>Program:</strong> {{ object.program }} <br>
            <strong>Level:</strong> {{ object.level }} <br>
            <strong>Term:</strong> {{ object.term }} <br>
            <strong>Exam Type:</strong> {{ object.get_exam_type_display }} <br>
            <strong>Duration:</strong> {{ object.start_date }} → {{ object.end_date }} <br>
            <strong>Status:</strong>
            {% if object.is_published %} Published {% else %} 
             <a href="{% url 'varsity_portal:exam_publish_toggle' object.id %}"
             class="btn btn-sm btn-outline-warning">⏳Click to Publish</a>
            {% endif %}
        </p>

        <hr>

        <h3>Exam Schedules</h3>

       
        <div class="table-responsive">
            <table border="1" cellpadding="8" class="table">
                <thead class="table-info">
                    <tr>
                        <th>Subject</th>
                        <th>Date</th>
                        <th>Time</th>
                        <th>Venue</th>
                        <th>Max Marks</th>
                       
                    </tr>
                </thead>
                <tbody>
                    {% for schedule in object.schedules.all %}
                    <tr>
                        <td>{{ schedule.subject_offering }}</td>
                        <td>{{ schedule.exam_date }}</td>
                        <td>{{ schedule.start_time }} - {{ schedule.end_time }}</td>
                        <td>{{ schedule.venue|default:"—" }}</td>
                        <td>{{ schedule.max_marks }}</td>
                       
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="6">No schedules added yet</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            </div>

        <hr>
        
    </div>
</div>

<a href="{% url 'varsity_portal:exam_list' %}">⬅ Back to Exam List</a>

{% endblock %}

templates/varsity_portal/exams/exam_list.html

{% extends "student_portal_base.html" %}
{% load custom_filters %}


{% block content %}
{% include 'varsity_portal/quick_access_link.html' %}

<h2>Exam List</h2>

<div class="table-responsive">
    <table border="1" cellpadding="8" class="table">
        <thead class="table-dark">
            <tr>
                <th>Admit card</th>               
                <th>Program</th>
                <th>Session</th>
                <th>Academic Year</th>
                <th>Term</th>
                <th>Exam Type</th>              
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for exam in exams %}
            <tr>
                 <td>
                    {% if not exam.exam_registrations.exists %}
                    <a href="{% url 'varsity_portal:register_for_exam' exam.id %}"
                    class="btn btn-sm btn-outline-primary">Register to get Admit Card</a>
                    {% else %}
                    <a href="{% url 'varsity_portal:generate_admit_card' exam.exam_registrations.first.id %}"
                    class="btn btn-sm btn-outline-primary">Admit Card</a>
                    {% endif %}
                 </td>
                 
                <td>{{ exam.program }}</td>
                <td>{{ exam.academic_session }}</td>
                <td>{{ exam.academic_year }}</td>
                <td>{{ exam.term }}</td>
                <td>{{ exam.get_exam_type_display }}</td>                
                
                <td>
                    <a href="{% url 'varsity_portal:exam_detail' exam.id %}">View</a>                    
                    
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="6">No exams found</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}